export const propertyData = [
  {
    floor: 2,
    bedroom: 3,
    kitchen: 1,
    living_room: 1,
    bathroom: 2,
    furnished: true,
    address: "Address 1",
    user_id: 1,
  },
  {
    floor: 2,
    bedroom: 3,
    kitchen: 1,
    living_room: 1,
    bathroom: 2,
    furnished: true,
    address: "Address 2",
    user_id: 1,
  },
  {
    floor: 2,
    bedroom: 3,
    kitchen: 1,
    living_room: 1,
    bathroom: 2,
    furnished: true,
    address: "Address 3",
    user_id: 1,
  },
  {
    floor: 2,
    bedroom: 3,
    kitchen: 1,
    living_room: 1,
    bathroom: 2,
    furnished: true,
    address: "Address 4",
    user_id: 2,
  },
  {
    floor: 2,
    bedroom: 3,
    kitchen: 1,
    living_room: 1,
    bathroom: 2,
    furnished: true,
    address: "Address 5",
    user_id: 2,
  },
];
