export const ratingData = [
  {
    comment: "Great experience!10",
    cleanliness_rating: 4.5,
    accuracy_rating: 4.0,
    check_in_rating: 5.0,
    communication_rating: 4.8,
    location_rating: 4.2,
    value_rating: 4.5,
  },
  {
    comment: "Great experience!11",
    cleanliness_rating: 4.5,
    accuracy_rating: 4.0,
    check_in_rating: 5.0,
    communication_rating: 4.8,
    location_rating: 4.2,
    value_rating: 4.5,
  },
  {
    comment: "Great experience!12",
    cleanliness_rating: 4.5,
    accuracy_rating: 4.0,
    check_in_rating: 5.0,
    communication_rating: 4.8,
    location_rating: 4.2,
    value_rating: 4.5,
  },
  {
    comment: "Great experience!2",
    cleanliness_rating: 4.5,
    accuracy_rating: 4.0,
    check_in_rating: 5.0,
    communication_rating: 4.8,
    location_rating: 4.2,
    value_rating: 4.5,
  },
  {
    comment: "Great experience!3",
    cleanliness_rating: 4.5,
    accuracy_rating: 4.0,
    check_in_rating: 5.0,
    communication_rating: 4.8,
    location_rating: 4.2,
    value_rating: 4.5,
  },
  {
    comment: "Great experience!4",
    cleanliness_rating: 4.5,
    accuracy_rating: 4.0,
    check_in_rating: 5.0,
    communication_rating: 4.8,
    location_rating: 4.2,
    value_rating: 4.5,
  },
  {
    comment: "Great experience!5",
    cleanliness_rating: 4.5,
    accuracy_rating: 4.0,
    check_in_rating: 5.0,
    communication_rating: 4.8,
    location_rating: 4.2,
    value_rating: 4.5,
  },
];
